-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 16:54:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mesadeayuda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mesadeayuda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mesadeayuda` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_mesadeayuda` ;

-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `cuit` VARCHAR(11) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  `emaill` VARCHAR(65) NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`servicios` (
  `id_servicios` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'si es aplicación( tango, sap, etc) o sistema operativo (linux,windows,etc)',
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_servicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`clientes_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`clientes_servicios` (
  `id_clientes` INT NOT NULL,
  `id_servicios` INT NOT NULL,
  INDEX `id_clientes_idx` (`id_clientes` ASC) VISIBLE,
  INDEX `id_servicios_idx` (`id_servicios` ASC) VISIBLE,
  PRIMARY KEY (`id_clientes`, `id_servicios`),
  CONSTRAINT `id_clientes`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `db_mesadeayuda`.`clientes` (`id_clientes`),
  CONSTRAINT `id_servicios`
    FOREIGN KEY (`id_servicios`)
    REFERENCES `db_mesadeayuda`.`servicios` (`id_servicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`especialidades` (
  `id_especialidades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especialidades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`tecnicos` (
  `id_tecnicos` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `tecnicoscol` VARCHAR(45) NULL,
  `medio_de_notificacion` VARCHAR(65) NULL,
  PRIMARY KEY (`id_tecnicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`incidentes` (
  `id_incidentes` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_servicios` INT NOT NULL,
  `id_especialidades` INT NOT NULL,
  `id_tecnicos` INT NOT NULL,
  `tiempo_estimado_resolucion` VARCHAR(30) NOT NULL,
  `fecha_posible_resolucion` DATE NOT NULL,
  `resuelto` VARCHAR(10) NOT NULL,
  `consideraciones` LONGTEXT NULL,
  PRIMARY KEY (`id_incidentes`),
  INDEX `idClientes_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `idTecnicos_idx` (`id_tecnicos` ASC) VISIBLE,
  INDEX `idServicios_idx` (`id_servicios` ASC) VISIBLE,
  INDEX `idEspecialidades_idx` (`id_especialidades` ASC) VISIBLE,
  CONSTRAINT `idClientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_mesadeayuda`.`clientes` (`id_clientes`),
  CONSTRAINT `idEspecialidades`
    FOREIGN KEY (`id_especialidades`)
    REFERENCES `db_mesadeayuda`.`especialidades` (`id_especialidades`),
  CONSTRAINT `idServicios`
    FOREIGN KEY (`id_servicios`)
    REFERENCES `db_mesadeayuda`.`servicios` (`id_servicios`),
  CONSTRAINT `idTecnicos`
    FOREIGN KEY (`id_tecnicos`)
    REFERENCES `db_mesadeayuda`.`tecnicos` (`id_tecnicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mesadeayuda`.`tecnicos_especialildades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesadeayuda`.`tecnicos_especialildades` (
  `id_tecnicos` INT NOT NULL,
  `id_especialidades` INT NOT NULL,
  INDEX `id_tecnicos_idx` (`id_tecnicos` ASC) VISIBLE,
  INDEX `id_especialidades_idx` (`id_especialidades` ASC) VISIBLE,
  PRIMARY KEY (`id_tecnicos`, `id_especialidades`),
  CONSTRAINT `id_especialidades`
    FOREIGN KEY (`id_especialidades`)
    REFERENCES `db_mesadeayuda`.`especialidades` (`id_especialidades`),
  CONSTRAINT `id_tecnicos`
    FOREIGN KEY (`id_tecnicos`)
    REFERENCES `db_mesadeayuda`.`tecnicos` (`id_tecnicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

clientes